### ISSUE TITLE
zc/__init__.py isn't distributed with pip

### ISSUE THREAD

**Issue by sofiacofler** [zopefoundation/zc.lockfile#13]
Hi,
When installing zc.lockfile-1.2.1.tar.gz with pip on Ubuntu 12.04 the __init__.py file doesn't exist under the zc folder.
I tried to uninstall and install the package but still the file is not deployed even though it can be found inside the tar.gz file.

Thanks,
Sofia

**Comment by icemac** [comment]
Looks similar to zopefoundation/zope.interface#68. But that one does not seem to be solved yet, too.

**Comment by sofiacofler** [comment]
zopefoundation/zope.interface#68 seems like the same issue in a different package of zopefuncation.
I encountered the problem while running my executable built with pyinstaller: 
"ImportError: No module named zc.lockfile"
This import is made by ZODB.FileStorage.

**Comment by mgedmin** [comment]
Should the `__init__.py` exist?  `zc` is a namespace package, and the setuptools magic that makes those work on Python 2.7 doesn't require an `__init__.py`, apparently:

```
$ virtualenv /tmp/sandbox
$ /tmp/sandbox/bin/pip install zc.lockfile
$ ls /tmp/sandbox/lib/python2.7/site-packages/zc
lockfile
$ /tmp/sandbox/bin/python
>>> import zc
>>> zc.__path__
['/tmp/sandbox/local/lib/python2.7/site-packages/zc', '/tmp/sandbox/lib/python2.7/site-packages/zc']
```

In other words, what actual problems does this cause?

**Comment by mgedmin** [comment]
> In other words, what actual problems does this cause?

Sorry, I didn't notice your comment!  The "ImportError: No module named zc.lockfile" is a problem.

I've never used pyinstaller before.  Some Google suggests older versions of pyinstaller didn't support namespace packages, but according to its changelog version 3.0 should support them fine.

Could you show us how to reproduce the problem with pyinstaller?

**Comment by sofiacofler** [comment]
@mgedmin no problem.
I reproduced the issue in my lab by creating a new simple program.
**My lab specs:**
_Ubuntu 12.04
Python 2.7.3
PyInstaller 3.2
ZODB 5.2.4
zc.lockfile 1.2.1_

**The code test.py:**
```
import ZODB, ZODB.FileStorage

if __name__ == '__main__':
   storage = ZODB.FileStorage.FileStorage("data.fs")
   db = ZODB.DB(storage)
   db.close()
   storage.close()
```

When run with python it works (which seems logical seeing your explenation before :-)):
`sudo python ./test.py`

For the PyInstaller you will need a minimal [spec file](https://pythonhosted.org/PyInstaller/spec-files.html#spec-file-operation) and then you need to run the following command:
`sudo python ~/Programs/PyInstaller-3.2/pyinstaller.py --onefile test.spec`
An executable will be created under the folder 'dist'.
Run the executable and you will see the following error:

```
   File "ZODB/FileStorage/FileStorage.py", line 29, in <module>
ImportError: No module names zc.lockfile
```

To temporary solve this issue I copied the zc/__init__.py file supplied in zc.lockfile-1.2.1.tar.gz  to the local zc installation directory and after rebuilding the executable, everything works just fine.

Thanks

**Comment by mgedmin** [comment]
Could you upload the test.spec file you used somewhere (e.g. gist.github.com, or just put it in a comment here if it's not too long)?

Also, could you tell us how you installed ZODB and zc.lockfile -- e.g. sudo pip install or something else (such as a virtualenv)?  What pip version (the one from Ubuntu 12.04 that you get if you sudo apt-get install python-pip)?

(I'm tempted to say it's a bug in PyInstaller.)

**Comment by kleptog** [comment]
Just want to point out that a directory without __init__.py is considered a namespace package now according to [PEP420](https://www.python.org/dev/peps/pep-0420/#specification), so quite a lot of packages these days ship without these __init__.py files and it's not a bug.

**Comment by AlanCoding** [comment]
@kleptog is correct. This was resolved in `setuptools` in https://github.com/pypa/setuptools/pull/1486. I hit the warning with `setuptools==39.0.1`.

```
(awx) bash-4.2# python -W error -c "from pkg_resources import load_entry_point"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/awx/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/venv/awx/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/venv/awx/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3065, in _initialize_master_working_set
    for dist in working_set
  File "/venv/awx/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3065, in <genexpr>
    for dist in working_set
  File "/venv/awx/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2595, in activate
    declare_namespace(pkg)
  File "/venv/awx/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2163, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/venv/awx/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2083, in _handle_ns
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 426, in _find_module_shim
ImportWarning: Not importing directory /venv/awx/lib64/python3.6/site-packages/zope: missing __init__
```

I upgraded to `setuptools==41.0.0` and found it to be resolved.

```
(awx) bash-4.2# python -W error -c "from pkg_resources import load_entry_point"
(awx) bash-4.2# 
```

Fix actually landed in `setuptools==40.3.0`

https://setuptools.readthedocs.io/en/latest/history.html

> #1486: Suppress warnings in pkg_resources.handle_ns.

**Comment by icemac** [comment]
Solved in #31. It is no longer needed.
